Repository hashicorp/terraform-docs-common, pull requests merged in 2022-06, with the labels that each got.

#17 Update workspace creation documentation
  website/docs/cloud-docs/workspaces/creating.mdx
Labels: documentation, tw-reviewed, Terraform Cloud

#36 Add PR Template to Repository
  .github/pull_request_template.md
Labels: tw-reviewed

#35 Mention 'retry run' button in the viewing and managing runs page
  website/docs/cloud-docs/run/manage.mdx
Labels: tw-reviewed

#19 Microsoft Teams notifications documentation
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/workspaces/settings/notifications.mdx
  website/img/docs/notifications-all-types.png
  website/img/docs/notifications-email-sample.png
  website/img/docs/notifications-slack-sample.png
Labels: tw-reviewed, Terraform Cloud

#31 Explain storage freeing backfill capability for TFE
  website/docs/cloud-docs/workspaces/configurations.mdx
Labels: tw-reviewed

#38 Added private-providers api changelog
  website/docs/cloud-docs/api-docs/changelog.mdx
Labels: documentation

#29 Increase visibility and discoverability of API changelog
  website/docs/cloud-docs/api-docs/index.mdx
Labels: tw-reviewed

#26 Update Aqua's listing, trimmed, added docs
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: tw-reviewed

#43 registry/providers/publishing: Call out branch name overlapping and JSON syntax issues
  website/docs/registry/providers/publishing.mdx
Labels: clarification

#42 plugin: Include terraform-plugin-framework in protocol version 5 implementations
  website/docs/plugin/how-terraform-works.mdx
Labels: clarification, plugin, tw-reviewed

#45 Remove duplicate API changelog notice
  website/docs/cloud-docs/api-docs/index.mdx
Labels: documentation

#51 Missing tag query param
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: documentation

#55 Add Drift Detection Docs and Update Workspaces Notifications Page Content
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/workspaces/settings/drift-detection.mdx
  website/docs/cloud-docs/workspaces/settings/notifications.mdx
  website/img/docs/notifications-error.png
  website/img/docs/notifications-index.png
  website/img/docs/notifications-success.png
  website/img/docs/notifications-workspace-settings.png
Labels: new docs, Terraform Cloud

#47 update organizations page
  website/docs/cloud-docs/api-docs/admin/organizations.mdx
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/workspaces/index.mdx
Labels: documentation, tw-reviewed

#28 Add run task results/stages and update for post-plan
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-task-stages-and-results.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks-integration.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
  website/docs/cloud-docs/api-docs/run.mdx
Labels: documentation, Terraform Cloud

#48 TER-161-update run tasks documentation
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: tw-reviewed

#53 Assessments docs
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/assessment-results.mdx
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: documentation, new docs, tw-reviewed, Terraform Cloud
