Repository hashicorp/terraform-docs-common, pull requests merged in 2022-08, with the labels that each got.

#68 Add HCP account documentation in users page
  website/docs/cloud-docs/users-teams-organizations/users.mdx
Labels: tw-reviewed

#83 Add pre-plan beta notification to stages
  website/docs/cloud-docs/api-docs/run-tasks/run-task-stages-and-results.mdx
  website/docs/cloud-docs/run/states.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: documentation, tw-reviewed

#87 added oak9 and torq to the list
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: tw-reviewed

#91 fixed typo in oak9's branding
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: tw-reviewed

#71 Document sentinel policy support in the public registry
  website/data/registry-nav-data.json
  website/docs/registry/index.mdx
  website/docs/registry/policy-libraries/publishing.mdx
  website/docs/registry/policy-libraries/using-policies.mdx
  website/docs/registry/private.mdx
Labels: documentation, tw-reviewed

#92 registry/providers/publishing: Clarify Terraform Plugin Framework protocol version description
  website/docs/registry/providers/publishing.mdx
Labels: clarification, plugin, tw-reviewed

#95 plugin: Add framework v0.11.0 resource private state handling to Which SDK? page
  website/docs/plugin/which-sdk.mdx
Labels: documentation, plugin

#64 Update documentation for triggering workspace runs with Git tags
  website/docs/cloud-docs/api-docs/workspaces.mdx
  website/docs/cloud-docs/run/ui.mdx
  website/docs/cloud-docs/workspaces/settings/vcs.mdx
Labels: tw-reviewed

#98 adding character limits to run task description
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
Labels: tw-reviewed

#102 Add list gpg-keys endpoint to private registry docs
  website/docs/cloud-docs/api-docs/private-registry/gpg-keys.mdx
Labels: documentation, tw-reviewed, Terraform Cloud

#62 Update bitbucket-server.mdx
  website/docs/cloud-docs/vcs/bitbucket-server.mdx
Labels: tw-reviewed

#103 Update Docs for DevDot Migration
  website/docs/cloud-docs/api-docs/index.mdx
  website/docs/cloud-docs/api-docs/state-versions.mdx
  website/docs/cloud-docs/cost-estimation/index.mdx
  website/docs/cloud-docs/index.mdx
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
  website/docs/cloud-docs/migrate/index.mdx
  website/docs/cloud-docs/overview.mdx
  website/docs/cloud-docs/recommended-practices/part3.1.mdx
  website/docs/cloud-docs/registry/add.mdx
  website/docs/cloud-docs/registry/index.mdx
  website/docs/cloud-docs/registry/publish-modules.mdx
  website/docs/cloud-docs/registry/using.mdx
  website/docs/cloud-docs/run/api.mdx
  website/docs/cloud-docs/run/cli.mdx
  website/docs/cloud-docs/run/modes-and-options.mdx
  website/docs/cloud-docs/run/remote-operations.mdx
  website/docs/cloud-docs/sentinel/enforce.mdx
  website/docs/cloud-docs/sentinel/examples.mdx
  website/docs/cloud-docs/sentinel/index.mdx
  website/docs/cloud-docs/sentinel/manage-policies.mdx
  website/docs/cloud-docs/users-teams-organizations/permissions.mdx
  website/docs/cloud-docs/users-teams-organizations/teams.mdx
  website/docs/cloud-docs/users-teams-organizations/users.mdx
  website/docs/cloud-docs/workspaces/creating.mdx
  website/docs/cloud-docs/workspaces/index.mdx
  website/docs/cloud-docs/workspaces/settings/drift-detection.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
  website/docs/cloud-docs/workspaces/settings/run-triggers.mdx
  website/docs/cloud-docs/workspaces/variables/index.mdx
  website/docs/cloud-docs/workspaces/variables/managing-variables.mdx
  website/docs/docs/index.mdx
  website/docs/plugin/index.mdx
  website/docs/registry/providers/docs.mdx
  website/docs/registry/providers/publishing.mdx
Labels: clarification, tw-reviewed

#110 Add Exclusion Frontmatter for TFC-Only Docs
  website/docs/cloud-docs/api-docs/ip-ranges.mdx
  website/docs/cloud-docs/architectural-details/index.mdx
  website/docs/cloud-docs/architectural-details/ip-ranges.mdx
  website/docs/cloud-docs/architectural-details/security-model.mdx
  website/docs/cloud-docs/index.mdx
  website/docs/cloud-docs/integrations/kubernetes/index.mdx
  website/docs/cloud-docs/integrations/splunk/index.mdx
  website/docs/cloud-docs/overview.mdx
  website/docs/cloud-docs/recommended-practices/index.mdx
  website/docs/cloud-docs/recommended-practices/part1.mdx
  website/docs/cloud-docs/recommended-practices/part2.mdx
  website/docs/cloud-docs/recommended-practices/part3.1.mdx
  website/docs/cloud-docs/recommended-practices/part3.2.mdx
  website/docs/cloud-docs/recommended-practices/part3.3.mdx
  website/docs/cloud-docs/recommended-practices/part3.4.mdx
  website/docs/cloud-docs/recommended-practices/part3.mdx
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/azure-ad.mdx
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/index.mdx
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/linking-user-account.mdx
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/okta.mdx
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/saml.mdx
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/testing.mdx
  website/docs/cloud-docs/vcs/github-app.mdx
  website/docs/cloud-docs/workspaces/settings/drift-detection.mdx
Labels: documentation, Terraform Cloud

#113 Update documentation with outbound IP ranges
  website/docs/cloud-docs/api-docs/ip-ranges.mdx
Labels: documentation, tw-reviewed

#108 Add pre-apply task stage information for a Run
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-task-stages-and-results.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
  website/docs/cloud-docs/run/states.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: documentation, tw-reviewed

#105 add query parameters language to organizations API List Org endpoint
  website/docs/cloud-docs/api-docs/organizations.mdx
Labels: tw-reviewed
