Repository hashicorp/terraform-docs-common, pull requests merged in 2022-10, with the labels that each got.

#157 removing duplicate paragraph
  website/docs/docs/partnerships.mdx
Labels: tw-reviewed

#158 Add more details about `terraform.tfvars`
  website/docs/cloud-docs/workspaces/variables/index.mdx
Labels: clarification, Terraform Cloud

#168 repo sync
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/assessment-results.mdx
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/api-docs/private-registry/modules.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-task-stages-and-results.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
  website/docs/cloud-docs/no-code-provisioning/module-design.mdx
  website/docs/cloud-docs/no-code-provisioning/provisioning.mdx
  website/docs/cloud-docs/overview.mdx
  website/docs/cloud-docs/policy-enforcement/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
  website/docs/cloud-docs/policy-enforcement/opa/index.mdx
  website/docs/cloud-docs/policy-enforcement/opa/vcs.mdx
  website/docs/cloud-docs/policy-enforcement/policy-results.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfrun.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/index.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/json.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/mock.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/sentinel-tf-012.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/vcs.mdx
  website/docs/cloud-docs/registry/add.mdx
  website/docs/cloud-docs/registry/publish-modules.mdx
  website/docs/cloud-docs/registry/using.mdx
  website/docs/cloud-docs/run/states.mdx
  website/docs/cloud-docs/run/ui.mdx
  website/docs/cloud-docs/sentinel/enforce.mdx
  website/docs/cloud-docs/sentinel/examples.mdx
  website/docs/cloud-docs/sentinel/index.mdx
  website/docs/cloud-docs/sentinel/manage-policies.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations.mdx
  website/docs/cloud-docs/workspaces/creating.mdx
  website/docs/cloud-docs/workspaces/health.mdx
  website/docs/cloud-docs/workspaces/index.mdx
  website/docs/cloud-docs/workspaces/settings/health-assessments.mdx
  website/docs/cloud-docs/workspaces/settings/index.mdx
  website/docs/cloud-docs/workspaces/settings/notifications.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: automated-reposync-pr

#161 change spectralops to check point
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: tw-reviewed

#21 Add `tfe_outputs` note to Run Triggers page to match the Remote State page
  website/docs/cloud-docs/workspaces/settings/run-triggers.mdx
Labels: tw-reviewed

#170 Update changelog.mdx
  website/docs/cloud-docs/api-docs/changelog.mdx
Labels: tw-reviewed

#175 New notification trigger type for CV
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
Labels: documentation

#173 Update team members documentation
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/team-members.mdx
Labels: documentation, tw-reviewed, Terraform Cloud

#146 Deleting workspaces with resources under management
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/organizations.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations.mdx
  website/docs/cloud-docs/users-teams-organizations/permissions.mdx
  website/docs/cloud-docs/workspaces/settings/index.mdx
Labels: documentation, enhancement, Terraform Cloud

#169 Remove beta flags for run tasks
  website/docs/cloud-docs/api-docs/run-tasks/run-task-stages-and-results.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks-integration.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
  website/docs/cloud-docs/run/states.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
  website/docs/docs/partnerships.mdx
Labels: documentation, Terraform Cloud

#182 adding blink and tines for pre-plan GA
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: tw-reviewed

#183 fixing a minor error on the tines url
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: tw-reviewed

#189 updating tines description
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: tw-reviewed

#181 add language to include wildcard search feature
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: tw-reviewed

#185 Update partnerships.mdx
  website/docs/docs/partnerships.mdx
Labels: tw-reviewed

#172 Add errored result counts and filter parameter details to Policy Checks API docs
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/policy-checks.mdx
Labels: documentation, tw-reviewed, Terraform Cloud

#122 Fix broken link for the configuration-free GitHub App
  website/docs/cloud-docs/vcs/github.mdx
Labels: tw-reviewed

#190 add reauthorizing vcs oauth providers to troubleshooting page
  website/docs/cloud-docs/vcs/troubleshooting.mdx
Labels: tw-reviewed
