Repository hashicorp/terraform-docs-common, pull requests merged in 2022-12, with the labels that each got.

#67 Add a table to show the full list of supported tfce resources
  website/docs/cloud-docs/cost-estimation/aws.mdx
  website/docs/cloud-docs/cost-estimation/azure.mdx
  website/docs/cloud-docs/cost-estimation/gcp.mdx
Labels: documentation, clarification, tw-reviewed, Terraform Cloud

#224 Show "agent-count" field in Agent Pools response
  website/docs/cloud-docs/api-docs/agents.mdx
Labels: tw-reviewed

#226 Update which-sdk.mdx
  website/docs/plugin/which-sdk.mdx
Labels: documentation, tw-reviewed

#225 Fix hyperlink on CLI driven runs page
  website/docs/cloud-docs/run/cli.mdx
Labels: tw-reviewed

#227 TFC API docs: Add information about async processing of state version info
  website/docs/cloud-docs/api-docs/state-version-outputs.mdx
  website/docs/cloud-docs/api-docs/state-versions.mdx
Labels: documentation, clarification, Terraform Cloud
