Repository hashicorp/terraform-docs-common, pull requests merged in 2023-05, with the labels that each got.

#322 TFC Integrations - ServiceNow Service Catalog - version update and Agents Support feature
  website/docs/cloud-docs/integrations/service-now/index.mdx
  website/docs/cloud-docs/integrations/service-now/service-catalog.mdx
Labels: documentation

#343 Document new TFC_VAULT_ENCODED_CACERT environment variable
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-configuration.mdx
Labels: documentation, Terraform Cloud

#348 Fix image name
  website/img/docs/tfc-plan-summary.png
Labels: bug, Terraform Cloud

#349 Clarifiy that versioned policy sets are included in TFC Plus
  website/docs/cloud-docs/api-docs/policies.mdx
  website/docs/cloud-docs/api-docs/policy-checks.mdx
  website/docs/cloud-docs/api-docs/policy-set-params.mdx
  website/docs/cloud-docs/api-docs/policy-sets.mdx
  website/docs/cloud-docs/overview/index.mdx
  website/docs/cloud-docs/policy-enforcement/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
  website/docs/cloud-docs/policy-enforcement/opa/index.mdx
  website/docs/cloud-docs/policy-enforcement/opa/vcs.mdx
  website/docs/cloud-docs/policy-enforcement/policy-results.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfrun.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/index.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/json.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/mock.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/sentinel-tf-012.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/vcs.mdx
  website/docs/cloud-docs/run/cli.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations.mdx
Labels: documentation, clarification, Terraform Cloud

#351 Update wording of policy callout
  website/docs/cloud-docs/api-docs/policies.mdx
  website/docs/cloud-docs/api-docs/policy-checks.mdx
  website/docs/cloud-docs/api-docs/policy-set-params.mdx
  website/docs/cloud-docs/api-docs/policy-sets.mdx
  website/docs/cloud-docs/overview/index.mdx
  website/docs/cloud-docs/policy-enforcement/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
  website/docs/cloud-docs/policy-enforcement/opa/index.mdx
  website/docs/cloud-docs/policy-enforcement/opa/vcs.mdx
  website/docs/cloud-docs/policy-enforcement/policy-results.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfrun.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/index.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/json.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/mock.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/sentinel-tf-012.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/vcs.mdx
  website/docs/cloud-docs/run/cli.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations.mdx
Labels: documentation, clarification, Terraform Cloud

#346 TF-6596-Exposes-More-Properties-to-TFRun
  website/docs/cloud-docs/policy-enforcement/opa/index.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfrun.mdx
Labels: Terraform Cloud, Policies

#356 Remove note about unversioned policies
  website/docs/cloud-docs/api-docs/policies.mdx
Labels: documentation

#359 Add Estimating Cost document
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/overview/estimate-terraform-cloud-cost.mdx
  website/img/docs/tfc-org-usage.png
  website/img/docs/tfc-payg-example.png
  website/img/docs/tfc-upgrade-plan.png
Labels: documentation, Terraform Cloud

#353 Update Run Task payload request
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks-integration.mdx
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
Labels: documentation

#357 Update run tasks description
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: documentation

#350 Add corresponding TFE edits to TFC
  website/docs/cloud-docs/api-docs/organization-tokens.mdx
  website/docs/cloud-docs/api-docs/team-tokens.mdx
  website/docs/cloud-docs/users-teams-organizations/api-tokens.mdx
  website/docs/cloud-docs/users-teams-organizations/users.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-configuration.mdx
Labels: documentation

#358 Add docs for Workspaces Settings > Policies
  website/docs/cloud-docs/workspaces/settings/index.mdx
Labels: documentation

#355 Update entitlement set, feature set, subscription and policy API endpoints after new free tier
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/feature-sets.mdx
  website/docs/cloud-docs/api-docs/organizations.mdx
  website/docs/cloud-docs/api-docs/policies.mdx
  website/docs/cloud-docs/api-docs/subscriptions.mdx
Labels: documentation, Terraform Cloud, Policies
