Repository hashicorp/terraform-docs-common, pull requests merged in 2023-06, with the labels that each got.

#361 Add reference to Registry Publishing FAQ from index page
  website/docs/registry/index.mdx
Labels: enhancement

#360 Add TFC exclusion tags for all PnP related callouts
  website/docs/cloud-docs/api-docs/agent-tokens.mdx
  website/docs/cloud-docs/api-docs/agents.mdx
  website/docs/cloud-docs/api-docs/assessment-results.mdx
  website/docs/cloud-docs/api-docs/audit-trails.mdx
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/api-docs/policies.mdx
  website/docs/cloud-docs/api-docs/policy-checks.mdx
  website/docs/cloud-docs/api-docs/policy-set-params.mdx
  website/docs/cloud-docs/api-docs/policy-sets.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-task-stages-and-results.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks-integration.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
  website/docs/cloud-docs/api-docs/teams.mdx
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
  website/docs/cloud-docs/integrations/service-now/index.mdx
  website/docs/cloud-docs/integrations/service-now/service-catalog.mdx
  website/docs/cloud-docs/integrations/splunk/index.mdx
  website/docs/cloud-docs/no-code-provisioning/module-design.mdx
  website/docs/cloud-docs/no-code-provisioning/provisioning.mdx
  website/docs/cloud-docs/overview/index.mdx
  website/docs/cloud-docs/policy-enforcement/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
  website/docs/cloud-docs/policy-enforcement/opa/index.mdx
  website/docs/cloud-docs/policy-enforcement/opa/vcs.mdx
  website/docs/cloud-docs/policy-enforcement/policy-results.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfrun.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate-v2.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/index.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/json.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/mock.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/sentinel-tf-012.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/vcs.mdx
  website/docs/cloud-docs/run/cli.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations.mdx
  website/docs/cloud-docs/users-teams-organizations/teams.mdx
  website/docs/cloud-docs/workspaces/health.mdx
  website/docs/cloud-docs/workspaces/index.mdx
  website/docs/cloud-docs/workspaces/organize-workspaces-with-projects.mdx
  website/docs/cloud-docs/workspaces/settings/notifications.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: documentation, clarification, Terraform Cloud

#373 repo sync
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/workspaces/explorer.mdx
  website/docs/cloud-docs/workspaces/health.mdx
  website/docs/cloud-docs/workspaces/index.mdx
  website/img/docs/terraform-cloud-explorer-landing-page.png
Labels: automated-reposync-pr

#367 Update Workspaces API for project
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: documentation

#374 No Code Provisioning preparation for TFE
  website/docs/cloud-docs/api-docs/no-code-provisioning.mdx
  website/docs/cloud-docs/api-docs/private-registry/modules.mdx
  website/docs/cloud-docs/no-code-provisioning/module-design.mdx
  website/docs/cloud-docs/no-code-provisioning/provisioning.mdx
  website/docs/cloud-docs/registry/add.mdx
  website/docs/cloud-docs/registry/publish-modules.mdx
  website/docs/cloud-docs/registry/using.mdx
  website/docs/cloud-docs/workspaces/creating.mdx
  website/docs/cloud-docs/workspaces/index.mdx
Labels: documentation

#372 Mark pricing pages as TFC only and fix corresponding small style issues in TFE.
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/organizations.mdx
  website/docs/cloud-docs/api-docs/policies.mdx
  website/docs/cloud-docs/overview/change-plan.mdx
  website/docs/cloud-docs/overview/estimate-terraform-cloud-cost.mdx
  website/docs/cloud-docs/policy-enforcement/opa/index.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfrun.mdx
  website/docs/cloud-docs/users-teams-organizations/users.mdx
Labels: documentation

#376 Small link fix
  website/docs/cloud-docs/no-code-provisioning/provisioning.mdx
Labels: documentation

#370 TF-7064 Update Policy Sets PATCH endpoint
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/policy-sets.mdx
Labels: documentation, Terraform Cloud
