Repository hashicorp/terraform-docs-common, pull requests merged in 2024-05, with the labels that each got.

#625 HCP Terraform Agents - [Merge on 5/1]
  website/docs/cloud-docs/api-docs/applies.mdx
  website/docs/cloud-docs/api-docs/plans.mdx
  website/docs/cloud-docs/api-docs/policy-evaluations.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
  website/docs/cloud-docs/architectural-details/security-model.mdx
  website/docs/cloud-docs/integrations/kubernetes/api-reference.mdx
  website/docs/cloud-docs/overview/index.mdx
  website/docs/cloud-docs/run/remote-operations.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations/index.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/aws-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/azure-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/gcp-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/index.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/kubernetes-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/manual-generation.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/specifying-multiple-configurations.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/aws-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/azure-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/gcp-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/index.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-configuration.mdx
  website/docs/cloud-docs/workspaces/settings/index.mdx
  website/docs/cloud-docs/workspaces/variables/index.mdx
  website/img/docs/organization-vcs-general-aggregated-status-checks.png
  website/img/docs/organization-vcs-general-non-aggregated-status-checks.png
Labels: documentation

#624 bitbucket and other providers mentioned in the warning are supported now
  website/docs/cloud-docs/api-docs/oauth-clients.mdx
Labels: documentation

#626 A couple more agent references
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/applies.mdx
  website/docs/cloud-docs/api-docs/audit-trails.mdx
  website/docs/cloud-docs/api-docs/plans.mdx
  website/docs/cloud-docs/api-docs/policy-sets.mdx
  website/docs/cloud-docs/integrations/kubernetes/api-reference.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
Labels: documentation

#41 update Azure AD docs
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/azure-ad.mdx
Labels: tw-reviewed

#96 Update Azure AD SSO docs
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/azure-ad.mdx
Labels: tw-reviewed

#176 Link customers to TFE_PARALLELISM knowledge base rather than ask them to cut tickets
  website/docs/cloud-docs/workspaces/variables/index.mdx
Labels: tw-reviewed

#186 Add newline to fix note formatting
  website/docs/cloud-docs/policy-enforcement/policy-results.mdx
Labels: bug

#217 the word 'recommend' is missing
  website/docs/cloud-docs/architectural-details/security-model.mdx
Labels: tw-reviewed

#232 fixes-typo
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig-v2.mdx
Labels: tw-reviewed

#236 Update ip-ranges.mdx
  website/docs/cloud-docs/architectural-details/ip-ranges.mdx
Labels: tw-reviewed

#590 docs: updated Bibucket requirements to atleast v8.0 as from v202309-1
  website/docs/cloud-docs/vcs/bitbucket-data-center.mdx
Labels: documentation, clarification

#627 Update billing UI screenshots for PAYG [IPE-710]
  website/docs/cloud-docs/overview/activate-flex.mdx
  website/docs/cloud-docs/overview/activate-payg.mdx
  website/img/docs/tfc-hcp-org-link.png
  website/img/docs/tfc-plan-summary.png
  website/img/docs/tfc-usage-summary.png
Labels: HCP Terraform

#632 Terraform Cloud for Splunk rebrand [IPE-726]
  website/docs/cloud-docs/integrations/splunk/index.mdx
Labels: HCP Terraform

#634 minor fixes and improvements to the run task callback API
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks-integration.mdx
Labels: documentation, HCP Terraform

#640 TF-13302: Adds Runs to Organization Settings
  website/docs/cloud-docs/users-teams-organizations/organizations/index.mdx
Labels: documentation

#620 hcp dynamic credentials guide
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/hcp-configuration.mdx
Labels: enhancement, HCP Terraform

#637 Document how to publish a new module version for a branch based module.
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/private-registry/modules.mdx
Labels: HCP Terraform

#646 Migrate workspace and project best practices
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/projects/best-practices.mdx
  website/docs/cloud-docs/workspaces/best-practices.mdx
  website/img/docs/workspace-net-infra-combined.png
  website/img/docs/workspace-net-infra-split.png
Labels: documentation, HCP Terraform

#633 [#TF-15260] add new manage-agent-pools permission to terraform docs
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/teams.mdx
  website/docs/cloud-docs/users-teams-organizations/permissions.mdx
  website/img/docs/terraform-cloud-authorization.png
Labels: documentation

#645 Remove maximum number of docs from registry storage limit
  website/docs/registry/providers/docs.mdx
Labels: documentation, clarification

#649 Correct configuration_version#create endpoint in example for tf test
  website/docs/cloud-docs/api-docs/private-registry/tests.mdx
Labels: HCP Terraform

#643 Update Terraform Test API section headers to ensure consistency
  website/docs/cloud-docs/api-docs/private-registry/tests.mdx
Labels: HCP Terraform
