Repository hashicorp/terraform-docs-common, pull requests merged in 2024-07, with the labels that each got.

#644 Add documentation for audit trails token
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/audit-trails-tokens.mdx
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/index.mdx
  website/docs/cloud-docs/integrations/splunk/index.mdx
  website/docs/cloud-docs/users-teams-organizations/api-tokens.mdx
Labels: documentation, HCP Terraform

#676 Update health assessment interval
  website/docs/cloud-docs/workspaces/health.mdx
Labels: documentation, HCP Terraform

#675 fixes broken link to sentinel docs
  website/docs/cloud-docs/run/states.mdx
Labels: bug, HCP Terraform

#660 Fix a typo in Runs API docs
  website/docs/cloud-docs/api-docs/run.mdx
Labels: documentation, HCP Terraform

#659 Update azure-configuration.mdx table
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/azure-configuration.mdx
Labels: documentation

#679 [TF-18462] Update docs to add locked-reason attr to workspace resp body
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: HCP Terraform

#674 Add Documentation for Allow Member Token Management
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/users-teams-organizations/api-tokens.mdx
  website/docs/cloud-docs/users-teams-organizations/permissions.mdx
Labels: documentation, HCP Terraform

#678 Add beta tag to audit token docs
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/audit-trails-tokens.mdx
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/index.mdx
  website/docs/cloud-docs/users-teams-organizations/api-tokens.mdx
Labels: documentation, HCP Terraform

#680 Update terraform test variable documentation to include format restrictions for var keys.
  website/docs/cloud-docs/api-docs/private-registry/tests.mdx
Labels: HCP Terraform

#655 Add a new workspace filter option to HCP Terraform API docs
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: HCP Terraform

#684 Docs/omit audit trails token api tfe
  website/docs/cloud-docs/api-docs/audit-trails-tokens.mdx
  website/docs/cloud-docs/api-docs/index.mdx
  website/docs/cloud-docs/api-docs/no-code-provisioning.mdx
  website/docs/cloud-docs/api-docs/private-registry/modules.mdx
  website/docs/cloud-docs/users-teams-organizations/api-tokens.mdx
Labels: documentation

#686 Add blog reference
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/index.mdx
Labels: documentation

#685 Updates no-code API docs
  website/docs/cloud-docs/api-docs/no-code-provisioning.mdx
Labels: documentation, HCP Terraform

#672 ServiceNow Service Graph Connector for Terraform - app version update
  website/docs/cloud-docs/integrations/service-now/service-graph/index.mdx
  website/img/docs/service-now-service-graph-design.png
Labels: documentation, HCP Terraform, ServiceNow

#688 Enhancements for the HCP Terraform Operator for Kubernetes
  website/docs/cloud-docs/integrations/kubernetes/annotations-and-labels.mdx
  website/docs/cloud-docs/integrations/kubernetes/api-reference.mdx
  website/docs/cloud-docs/integrations/kubernetes/index.mdx
  website/docs/cloud-docs/integrations/kubernetes/ops-v2-migration.mdx
  website/docs/cloud-docs/integrations/kubernetes/setup.mdx
  website/docs/docs/terraform-tools.mdx
Labels: documentation, HCP Terraform
