Repository hashicorp/terraform-docs-common, pull requests merged in 2024-10, with the labels that each got.

#740 Updated workspace best practices doc with workplace design
  website/docs/cloud-docs/workspaces/best-practices.mdx
Labels: Well Architected Framework

#743 VAULT-20139 Add information about how user_claim=workspace can affect client counts when renaming
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-configuration.mdx
Labels: clarification, HCP Terraform

#746 Update Run API page with new available filter
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/run.mdx
Labels: documentation, HCP Terraform

#749 Add docs for VCS Speculative Plan Management
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/run/ui.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations/index.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations/vcs-speculative-plan-management.mdx
Labels: documentation, HCP Terraform

#756 Improved SSO documentation
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/index.mdx
Labels: documentation

#751 Updates HCP Terraform Microsoft SSO docs
  website/docs/cloud-docs/users-teams-organizations/single-sign-on/entra-id.mdx
  website/img/docs/settings-azure.png
  website/img/docs/settings-entra.png
  website/img/docs/setup.png
  website/img/docs/wizard-choose-provider-azure.png
  website/img/docs/wizard-choose-provider-entra.png
  website/img/docs/wizard-configure-settings-azure.png
  website/img/docs/wizard-configure-settings-entra.png
Labels: question, clarification, HCP Terraform

#755 corrupted documentation table with missing text
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: documentation

#748 Add a troubleshooting tips section to ServiceNow Service Catalog documentation.
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/integrations/service-now/service-catalog-terraform/troubleshoot.mdx
Labels: documentation, HCP Terraform, ServiceNow

#761 adds to sample state version API response
  website/docs/cloud-docs/api-docs/state-versions.mdx
Labels: documentation, HCP Terraform

#769 Update HCP Operator Labels documentation
  website/docs/cloud-docs/integrations/kubernetes/annotations-and-labels.mdx
Labels: documentation, HCP Terraform
