Repository hashicorp/terraform-docs-common, pull requests merged in 2024-09, with the labels that each got.

#726 Add deprecation notice to Policy Check documentation
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/policy-checks.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
Labels: documentation

#727 Hcrhall/add-sentinel-plugin-deprecation-notices
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfconfig.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfplan.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfstate.mdx
Labels: documentation

#728 Remove beta note on on-demand evaluations
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
Labels: documentation, clarification

#729 Fix links in Vault-backed dynamic creds docs
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/aws-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/azure-configuration.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/vault-backed/gcp-configuration.mdx
Labels: documentation

#732 added expiry time(24hrs) to archivist link section
  website/docs/cloud-docs/architectural-details/security-model.mdx
Labels: documentation, HCP Terraform

#733 added note about HC API service account
  website/docs/cloud-docs/api-docs/teams.mdx
Labels: documentation, HCP Terraform

#734 minor update, remove expiry specifics
  website/docs/cloud-docs/architectural-details/security-model.mdx
Labels: documentation, HCP Terraform

#735 correct relationships to attributes
  website/docs/cloud-docs/api-docs/policy-sets.mdx
Labels: documentation, HCP Terraform

#731 Docs/redirs lang cli pr 35668
  website/redirects.js
Labels: documentation

#738 Docs/add changelog
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/changelog.mdx
Labels: documentation

#736 Add new run UI functionality to Organization settings Runs page
  website/docs/cloud-docs/users-teams-organizations/organizations/index.mdx
Labels: documentation

#699 docs: add documentation to support the beta release of resource tags
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/projects.mdx
  website/docs/cloud-docs/api-docs/reserved-tag-keys.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
  website/docs/partials/api-code-blocks/workspace-with-vcs.mdx
  website/docs/partials/api-code-blocks/workspace.mdx
  website/docs/partials/api-code-blocks/workspaces-list.mdx
Labels: documentation, enhancement, do not merge
