Repository hashicorp/terraform-docs-common, pull requests merged in 2024-11, with the labels that each got.

#768 Update Organizations API docs for speculative-plan-management-enabled
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/organizations.mdx
Labels: HCP Terraform

#774 fix: corrected the name of the test file
  website/docs/cloud-docs/policy-enforcement/sentinel/mock.mdx
Labels: documentation, HCP Terraform

#775 Adds tag_bindings to tfrun policy data
  website/docs/cloud-docs/policy-enforcement/sentinel/import/tfrun.mdx
Labels: HCP Terraform

#779 Add Ephemeral Resources to registry provider documentation
  website/docs/registry/providers/docs.mdx
Labels: plugin

#785 Policy Set params are now enabled for managed policy sets
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets.mdx
Labels: documentation, Policies
