Repository hashicorp/terraform-docs-common, pull requests merged in 2024-06, with the labels that each got.

#651 Docs/update migrate state instructions
  website/docs/cloud-docs/migrate/index.mdx
Labels: documentation

#650 Clarify the behavior of updating the designated no-code version
  website/docs/cloud-docs/no-code-provisioning/provisioning.mdx
Labels: documentation

#656 Update API docs to consistently refer to user ID as the same thing
  website/docs/cloud-docs/api-docs/team-members.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: documentation

#653 Adding Agent Pool associations to OAuth Client for Private VCS
  website/docs/cloud-docs/api-docs/oauth-clients.mdx
Labels: documentation

#657 Add HCP `auth_method` attribute
  website/docs/cloud-docs/api-docs/account.mdx
  website/docs/cloud-docs/api-docs/organization-memberships.mdx
  website/docs/cloud-docs/api-docs/users.mdx
Labels: documentation

#662 IPL-5982: Clarify that notifications won't be sent for speculative plans
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/workspaces/settings/notifications.mdx
Labels: clarification, HCP Terraform

#661 Add 503 response status to current state version outputs
  website/docs/cloud-docs/api-docs/state-version-outputs.mdx
Labels: documentation, HCP Terraform

#673 docs/plugin: Updated naming page headers
  website/docs/plugin/best-practices/naming.mdx
Labels: documentation, plugin
