Repository hashicorp/terraform-docs-common, pull requests merged in 2024-12, with the labels that each got.

#792 Docs/prewritten policies
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/policy-enforcement/define-policies/custom-sentinel.mdx
  website/docs/cloud-docs/policy-enforcement/define-policies/index.mdx
  website/docs/cloud-docs/policy-enforcement/define-policies/opa.mdx
  website/docs/cloud-docs/policy-enforcement/define-policies/prewritten-sentinel.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/index.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfconfig-v2.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfconfig.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfplan-v2.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfplan.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfrun.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfstate-v2.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfstate.mdx
  website/docs/cloud-docs/policy-enforcement/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/opa-vcs.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/sentinel-vcs.mdx
  website/docs/cloud-docs/policy-enforcement/sentinel/sentinel-tf-012.mdx
  website/docs/cloud-docs/policy-enforcement/test-sentinel.mdx
  website/docs/cloud-docs/policy-enforcement/view-results/index.mdx
  website/docs/cloud-docs/policy-enforcement/view-results/json.mdx
  website/redirects.js
Labels: documentation

#786 Clarify tag bindings and effective tag bindings API endpoints
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/projects.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: clarification, HCP Terraform

#799 Remove beta labels for policy evaluations
  website/docs/cloud-docs/api-docs/policy-sets.mdx
Labels: documentation, clarification

#800 Team visibility has previously been made generally available
  website/docs/cloud-docs/api-docs/teams.mdx
Labels: documentation, clarification

#802 fix typo
  website/data/cloud-docs-nav-data.json
Labels: documentation, Policies

#790 Add documentation for project-owned variable sets
  website/docs/cloud-docs/api-docs/variable-sets.mdx
  website/docs/cloud-docs/projects/best-practices.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations/index.mdx
  website/docs/cloud-docs/workspaces/variables/index.mdx
  website/docs/cloud-docs/workspaces/variables/managing-variables.mdx
Labels: documentation, HCP Terraform

#805 relocated prewritten sentinel topic
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/policy-enforcement/define-policies/custom-sentinel.mdx
  website/docs/cloud-docs/policy-enforcement/define-policies/opa.mdx
  website/docs/cloud-docs/policy-enforcement/prewritten-sentinel.mdx
  website/redirects.js
Labels: documentation, Policies

#788 PATCH workspace/project tag-bindings
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/projects.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: documentation, HCP Terraform
