Repository hashicorp/terraform-docs-common, pull requests merged in 2025-02, with the labels that each got.

#812 [DO NOT MERGE] - ServiceNow Service Catalog Version 2.8.0 Update
  website/docs/cloud-docs/integrations/service-now/service-catalog-terraform/index.mdx
  website/docs/cloud-docs/integrations/service-now/service-catalog-terraform/service-catalog-config.mdx
Labels: documentation, HCP Terraform, ServiceNow

#823 Linked Stacks Documentation
  website/docs/cloud-docs/stacks/deploy/plans.mdx
Labels: HCP Terraform

#817 Add documentation for the project variable sets permission
  website/docs/cloud-docs/users-teams-organizations/permissions.mdx
  website/docs/cloud-docs/workspaces/variables/managing-variables.mdx
Labels: documentation, enhancement, HCP Terraform

#810 Docs/enhanced tags public beta
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/projects/manage.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations/index.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations/manage-reserved-tags.mdx
  website/docs/cloud-docs/workspaces/browse.mdx
  website/docs/cloud-docs/workspaces/tags.mdx
Labels: documentation

#830 Adding an overview page for all Terraform integrations.
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/integrations/index.mdx
Labels: documentation, HCP Terraform, ServiceNow

#833 ServiceNow Service Graph - updating the list of supported ServiceNow versions.
  website/docs/cloud-docs/integrations/service-now/service-graph/service-graph-setup.mdx
Labels: documentation, HCP Terraform, do not merge, ServiceNow

#836 Updated all mentions of Enhanced to Agent in codebase
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/index.mdx
Labels: documentation, HCP Terraform, Policies

#841 Update Terraform migrate docs for GA
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/migrate/index.mdx
  website/docs/cloud-docs/migrate/tf-migrate/index.mdx
  website/docs/cloud-docs/migrate/tf-migrate/reference/configuration.mdx
  website/docs/cloud-docs/migrate/tf-migrate/reference/execute.mdx
  website/docs/cloud-docs/migrate/tf-migrate/reference/prepare.mdx
Labels: documentation, HCP Terraform

#846 Fix broken link in tf-migrate docs
  website/docs/cloud-docs/migrate/tf-migrate/index.mdx
Labels: bug, HCP Terraform
