Repository hashicorp/terraform-docs-common, pull requests merged in 2025-05, with the labels that each got.

#879 repo sync
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/feature-sets.mdx
  website/docs/cloud-docs/api-docs/index.mdx
  website/docs/cloud-docs/api-docs/organizations.mdx
  website/docs/cloud-docs/api-docs/private-registry/manage-module-versions.mdx
  website/docs/cloud-docs/api-docs/project-team-access.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks-integration.mdx
  website/docs/cloud-docs/api-docs/run-tasks/run-tasks.mdx
  website/docs/cloud-docs/api-docs/subscriptions.mdx
  website/docs/cloud-docs/api-docs/team-access.mdx
  website/docs/cloud-docs/api-docs/team-members.mdx
  website/docs/cloud-docs/integrations/splunk/index.mdx
  website/docs/cloud-docs/migrate/index.mdx
  website/docs/cloud-docs/overview/activate-flex.mdx
  website/docs/cloud-docs/overview/activate-payg.mdx
  website/docs/cloud-docs/overview/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/index.mdx
  website/docs/cloud-docs/registry/manage-module-versions.mdx
  website/docs/cloud-docs/registry/test.mdx
  website/docs/cloud-docs/run/run-environment.mdx
  website/docs/cloud-docs/vcs/private.mdx
  website/docs/cloud-docs/workspaces/best-practices.mdx
  website/docs/cloud-docs/workspaces/change-requests/index.mdx
  website/docs/cloud-docs/workspaces/index.mdx
  website/docs/cloud-docs/workspaces/settings/access.mdx
  website/docs/cloud-docs/workspaces/settings/run-tasks.mdx
  website/docs/partials/tfc-package-callouts/agents.mdx
  website/docs/partials/tfc-package-callouts/audit-trails.mdx
  website/docs/partials/tfc-package-callouts/aws-service-catalog.mdx
  website/docs/partials/tfc-package-callouts/change-requests.mdx
  website/docs/partials/tfc-package-callouts/ephemeral-workspaces.mdx
  website/docs/partials/tfc-package-callouts/health-assessments.mdx
  website/docs/partials/tfc-package-callouts/manage-module-versions.mdx
  website/docs/partials/tfc-package-callouts/nocode.mdx
  website/docs/partials/tfc-package-callouts/notifications.mdx
  website/docs/partials/tfc-package-callouts/policies.mdx
  website/docs/partials/tfc-package-callouts/private-vcs.mdx
  website/docs/partials/tfc-package-callouts/project-permissions.mdx
  website/docs/partials/tfc-package-callouts/project-workspaces.mdx
  website/docs/partials/tfc-package-callouts/run-tasks.mdx
  website/docs/partials/tfc-package-callouts/servicenow-catalog.mdx
  website/docs/partials/tfc-package-callouts/team-management.mdx
  website/docs/partials/tfc-package-callouts/tests.mdx
  website/img/docs/tfc-select-plan.png
Labels: automated-reposync-pr

#893 list endpoints with lower rate limits
  website/docs/cloud-docs/api-docs/index.mdx
Labels: documentation

#882 Add a note about additive/effective permissions
  website/docs/cloud-docs/users-teams-organizations/permissions.mdx
Labels: clarification

#901 [IPL-5408] Updating Docs for Pattern based Run Triggers
  website/docs/cloud-docs/workspaces/settings/vcs.mdx
Labels: documentation, HCP Terraform, rnd-india-tce

#912 add release notes section
  website/docs/docs/tools/mcp-server/index.mdx
Labels: documentation

#909 tf-migrate 1.1.0 documentation
  website/docs/cloud-docs/migrate/tf-migrate/index.mdx
  website/docs/cloud-docs/migrate/tf-migrate/reference/prepare.mdx
Labels: documentation

#913 Fix link to GitLab PAT documentation in tf-migrate overview
  website/docs/cloud-docs/migrate/tf-migrate/index.mdx
Labels: bug, documentation

#694 Fix auto destroy trigger typo
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
Labels: HCP Terraform

#638 cloud-docs/run-environment: Don't overload the term "run"
  website/docs/cloud-docs/run/run-environment.mdx
Labels: documentation, enhancement, clarification, HCP Terraform

#915 Update prompt.mdx
  website/docs/docs/tools/mcp-server/prompt.mdx
Labels: bug, documentation

#848 Add clarifying details for private module registry version attribute commit-sha
  website/docs/cloud-docs/api-docs/private-registry/modules.mdx
Labels: documentation, clarification, notified-of-UDR

#889 Update Flex Activation Docs
  website/docs/cloud-docs/overview/activate-flex.mdx
Labels: clarification, HCP Terraform, notified-of-UDR

#886 inherited-from link on effective tag bindings
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
Labels: HCP Terraform

#911 adding entry for prewritten-fsbp policies
  website/docs/cloud-docs/policy-enforcement/prewritten-library.mdx
  website/docs/cloud-docs/policy-enforcement/prewritten-sentinel.mdx
Labels: documentation

#890 update vcs int overview
  website/docs/cloud-docs/vcs/index.mdx
Labels: documentation

#587 tfc operator setup updates
  website/docs/cloud-docs/integrations/kubernetes/setup.mdx
Labels: documentation
