Repository hashicorp/terraform-docs-common, pull requests merged in 2025-04, with the labels that each got.

#878 Remove page that docuements migrating from legacy Team edition to Standard edition
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/overview/migrate-teams-standard.mdx
  website/redirects.js
Labels: HCP Terraform

#868 ServiceNow Service Graph Connector for Terraform - updated app version.
  website/docs/cloud-docs/integrations/service-now/service-graph/index.mdx
Labels: documentation, HCP Terraform, ServiceNow

#881 Clarify webhook / configuration version / manual run interactions
  website/docs/cloud-docs/run/ui.mdx
Labels: documentation, HCP Terraform

#880 Add note about VCS Events only being supported for Gitlab
  website/docs/cloud-docs/vcs/index.mdx
Labels: documentation, HCP Terraform

#884 Added ADO Services PAT documentation
  website/data/cloud-docs-nav-data.json
  website/docs/cloud-docs/vcs/azure-devops-server.mdx
  website/docs/cloud-docs/vcs/azure-devops-services-pat.mdx
  website/docs/cloud-docs/vcs/azure-devops-services.mdx
  website/docs/cloud-docs/vcs/index.mdx
Labels: documentation, new docs, HCP Terraform

#875 Add API Documentation for Multi-Team Tokens
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/team-tokens.mdx
  website/docs/cloud-docs/users-teams-organizations/api-tokens.mdx
  website/docs/cloud-docs/users-teams-organizations/permissions.mdx
Labels: documentation, HCP Terraform

#892 Remove mention of CLI runs using the Auto-Apply setting
  website/docs/cloud-docs/run/modes-and-options.mdx
  website/docs/cloud-docs/workspaces/settings/index.mdx
Labels: bug, HCP Terraform
