Repository hashicorp/terraform-docs-common, pull requests merged in 2025-03, with the labels that each got.

#822 Update Explorer API docs with new field current_rum_count
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/explorer.mdx
Labels: enhancement, HCP Terraform, do not merge

#851 Fix broken links to the HCP billing docs
  website/docs/cloud-docs/overview/activate-flex.mdx
  website/docs/cloud-docs/overview/activate-payg.mdx
  website/docs/cloud-docs/overview/index.mdx
  website/docs/cloud-docs/overview/migrate-teams-standard.mdx
Labels: bug, HCP Terraform

#770 Document unique pagination method used in Org Runs Index endpoint
  website/docs/cloud-docs/api-docs/changelog.mdx
  website/docs/cloud-docs/api-docs/run.mdx
Labels: HCP Terraform

#852 Add write-only argument names best practices section
  website/docs/plugin/best-practices/naming.mdx
Labels: documentation, plugin

#854 Move migration docs higher in nav
  website/data/cloud-docs-nav-data.json
Labels: documentation

#847 improve docs about setting up hcp operator
  website/docs/cloud-docs/integrations/kubernetes/setup.mdx
Labels: documentation

#860 Add ephemeral resource sections to provider best practices
  website/docs/plugin/best-practices/hashicorp-provider-design-principles.mdx
  website/docs/plugin/best-practices/sensitive-state.mdx
  website/docs/plugin/framework-benefits.mdx
Labels: documentation, plugin

#872 Correct typos in HCP workload identity commands
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/hcp-configuration.mdx
Labels: bug, documentation, HCP Terraform

#859 ServiceNow Service Catalog for Terraform - update version to 2.8.1.
  website/docs/cloud-docs/integrations/service-now/service-catalog-terraform/index.mdx
Labels: documentation, HCP Terraform, ServiceNow

#874 Remove comparison-description from feature-sets
  website/docs/cloud-docs/api-docs/feature-sets.mdx
  website/docs/cloud-docs/api-docs/subscriptions.mdx
Labels: documentation, HCP Terraform

#863 TF-24414 Add instructions on updating a stack's project
  website/docs/cloud-docs/stacks/configure.mdx
  website/docs/cloud-docs/stacks/deploy/plans.mdx
Labels: enhancement, HCP Terraform, do not merge
