Repository hashicorp/terraform-docs-common, pull requests merged in 2025-01, with the labels that each got.

#798 Update titles and descriptions for SEO and style guide
  website/docs/plugin/best-practices/hashicorp-provider-design-principles.mdx
  website/docs/plugin/best-practices/index.mdx
  website/docs/plugin/best-practices/interacting-with-providers.mdx
  website/docs/plugin/best-practices/naming.mdx
  website/docs/plugin/best-practices/provider-code.mdx
  website/docs/plugin/best-practices/sensitive-state.mdx
  website/docs/plugin/best-practices/versioning.mdx
  website/docs/plugin/code-generation/design.mdx
  website/docs/plugin/code-generation/framework-generator.mdx
  website/docs/plugin/code-generation/index.mdx
  website/docs/plugin/code-generation/openapi-generator.mdx
  website/docs/plugin/code-generation/specification.mdx
  website/docs/plugin/code-generation/workflow-example.mdx
  website/docs/plugin/debugging.mdx
  website/docs/plugin/framework-benefits.mdx
  website/docs/plugin/how-terraform-works.mdx
  website/docs/plugin/index.mdx
  website/docs/plugin/terraform-plugin-protocol.mdx
Labels: documentation

#747 Add information for behavior of workspace moving between project
  website/docs/cloud-docs/workspaces/settings/deletion.mdx
Labels: documentation, clarification

#816 Fix manage/mange typo
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/index.mdx
Labels: clarification, HCP Terraform

#818 All the little fixes from the TFE release
  website/docs/cloud-docs/api-docs/policy-set-params.mdx
  website/docs/cloud-docs/api-docs/projects.mdx
  website/docs/cloud-docs/api-docs/stability-policy.mdx
  website/docs/cloud-docs/api-docs/state-versions.mdx
  website/docs/cloud-docs/api-docs/variable-sets.mdx
  website/docs/cloud-docs/api-docs/workspace-variables.mdx
  website/docs/cloud-docs/api-docs/workspaces.mdx
  website/docs/cloud-docs/cost-estimation/index.mdx
  website/docs/cloud-docs/integrations/run-tasks/index.mdx
  website/docs/cloud-docs/integrations/service-now/service-catalog-terraform/troubleshoot.mdx
  website/docs/cloud-docs/integrations/service-now/service-graph/service-graph-setup.mdx
  website/docs/cloud-docs/migrate/tf-migrate/index.mdx
  website/docs/cloud-docs/policy-enforcement/define-policies/custom-sentinel.mdx
  website/docs/cloud-docs/policy-enforcement/define-policies/index.mdx
  website/docs/cloud-docs/policy-enforcement/define-policies/opa.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfconfig-v2.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfconfig.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfplan-v2.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfplan.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfrun.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfstate-v2.mdx
  website/docs/cloud-docs/policy-enforcement/import-reference/tfstate.mdx
  website/docs/cloud-docs/policy-enforcement/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/index.mdx
  website/docs/cloud-docs/policy-enforcement/manage-policy-sets/sentinel-vcs.mdx
  website/docs/cloud-docs/policy-enforcement/prewritten-sentinel.mdx
  website/docs/cloud-docs/policy-enforcement/test-sentinel.mdx
  website/docs/cloud-docs/policy-enforcement/view-results/json.mdx
  website/docs/cloud-docs/projects/manage.mdx
  website/docs/cloud-docs/run/modes-and-options.mdx
  website/docs/cloud-docs/run/states.mdx
  website/docs/cloud-docs/users-teams-organizations/organizations/index.mdx
  website/docs/cloud-docs/vcs/troubleshooting.mdx
  website/docs/cloud-docs/workspaces/dynamic-provider-credentials/hcp-vault-secrets-backed/index.mdx
  website/docs/cloud-docs/workspaces/tags.mdx
  website/docs/cloud-docs/workspaces/variables/index.mdx
  website/docs/cloud-docs/workspaces/variables/managing-variables.mdx
  website/docs/registry/policy-libraries/publishing.mdx
  website/docs/registry/policy-libraries/using-policies.mdx
Labels: HCP Terraform

#804 [Do not merge] Remove beta notices for MLM GA
  website/docs/cloud-docs/api-docs/change-requests.mdx
  website/docs/cloud-docs/api-docs/explorer.mdx
  website/docs/cloud-docs/api-docs/notification-configurations.mdx
  website/docs/cloud-docs/api-docs/private-registry/manage-module-versions.mdx
  website/docs/cloud-docs/registry/manage-module-versions.mdx
  website/docs/cloud-docs/users-teams-organizations/teams/notifications.mdx
  website/docs/cloud-docs/workspaces/change-requests/index.mdx
  website/docs/cloud-docs/workspaces/change-requests/manage.mdx
  website/docs/cloud-docs/workspaces/explorer.mdx
  website/docs/partials/api-code-blocks/workspace.mdx
  website/docs/partials/public-beta/manage-module-versions.mdx
Labels: HCP Terraform

#808 ServiceNow Service Graph Connector – updated app version.
  website/docs/cloud-docs/integrations/service-now/service-graph/index.mdx
Labels: documentation, HCP Terraform, ServiceNow

#820 Fix tf-migrate generated config directory name
  website/docs/cloud-docs/migrate/tf-migrate/reference/prepare.mdx
Labels: bug, HCP Terraform
